project:
  type: website
  output-dir: docs

website:
  title: "Rohan's Webpage"
  navbar:
    # background: "#102c3c"
    background: "#8C1515"
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - experience.qmd
      - blog.qmd

format:
  html:
    # theme: litera
    theme: 
      - simplex
      - theme.scss
    # good themes: spacelab, simplex, litera, default, united, flatly, cosmo 
    # css: styles.css
    toc: true
